# This config uses industrial_ci (https://github.com/ros-industrial/industrial_ci.git).
# For troubleshooting, see README (https://github.com/ros-industrial/industrial_ci/blob/master/README.rst)

name: Run ros-industrial CI

on: # this determines when this workflow is run
  push:
     branches: [ main ]
  pull_request:
     branches: [ main ]
  # schedule: # uncomment to run periodically
  #  - cron: '0 4 * * *' # every day at 4 AM (UTC)
  #workflow_dispatch: # allow manually starting this workflow

jobs:
  industrial_ci:
    name: ROS ${{ matrix.ROS_DISTRO }} (${{ matrix.ROS_REPO }})
    runs-on: ubuntu-latest
    strategy:
      # fail-fast: false # uncomment if failing jobs should not cancel the others immediately
      matrix: # matrix is the product of entries
        ROS_DISTRO: [noetic, jazzy]
        # exclude: # specific configuration can be excludes
        #   - {ROS_DISTRO: melodic, ROS_REPO: testing}
    #env:
    #  CCACHE_DIR: "${{ github.workspace }}/.ccache" # directory for ccache (and how we enable ccache in industrial_ci)
    steps:
      - uses: actions/checkout@v3 # clone target repository
      - uses: 'ros-industrial/industrial_ci@master' 
        env: # 
          ROS_DISTRO: ${{ matrix.ROS_DISTRO }}
